fix: connection list
vegaprotocol/vegawallet-ui pull request #178
Opened 2023-04-24 15:17 UTC by notbot00

# Related issues 🔗

Closes https://github.com/vegaprotocol/vegawallet-desktop/issues/656

# Description ℹ️

Making sure connections get displayed even when they have no assigned permissions to read any keys, etc.

2023-04-24 16:53 UTC, mattrussell36 requested changes

2023-04-24 16:53 UTC, mattrussell36 commented on libs/wallet-ui/src/components/connection-list/connection-list.tsx
> +  console.log(wallet)
chore (blocking): stray log

2023-04-24 16:53 UTC, mattrussell36 commented on libs/wallet-ui/src/components/connection-list/connection-manage.tsx
> +      <div className="p-[20px]">
chore (blocking): Can we just use p-5, mb-5 etc, they are the same, lets just use the default tw config spacing wherever possible

2023-04-24 16:53 UTC, mattrussell36 commented on libs/wallet-ui/src/components/connection-list/connection-manage.tsx
> +          <ButtonUnstyled className="p-0" onClick={onClose}>
suggestion (non blocking): Now that we are using tw I think using a bare `<button>` element is better than the `<ButtonUnstyled>` as tw will unset all styles. Not sure if you need additional spacing/padding here though

2023-04-25 07:59 UTC, notbot00 commented on libs/wallet-ui/src/components/connection-list/connection-list.tsx
> +  console.log(wallet)
```suggestion
```

2023-04-25 08:00 UTC, notbot00 commented on libs/wallet-ui/src/components/connection-list/connection-manage.tsx
> +      <div className="p-[20px]">
```suggestion
      <div className="p-5">
```

2023-04-25 08:09 UTC, notbot00 commented on libs/wallet-ui/src/components/connection-list/connection-manage.tsx
> +          <ButtonUnstyled className="p-0" onClick={onClose}>
changed this, will most likely need to do some conflict resolution with your PR, as there are other unstyled button components around in this component

2023-04-25 16:02 UTC, mattrussell36 approved these changes

2023-04-25 16:11 UTC, merged